#this is the default mapping for textures to their file names

furnace: furnace.png
doorWood: doorWood.png
doorIron: doorIron.png
ironBars: ironBars.png
railPowered: railPowered.png
railDetector: railDetector.png
railNormal: railNormal.png
restoneWire: restoneWire.png
redstoneTorch: redstoneTorch.png
redstoneRepeater: redstoneRepeater.png
piston: piston.png
lever: lever.png
doorTrap: doorTrap.png
tnt: tnt.png
stoneSlab: stoneSlab.png
ladder: ladder.png
torch: torch.png
dispenser: dispenser.png
cake: cake.png
bed: bed.png
bookshelf: bookshelf.png
brewingStand: brewingStand.png
cauldron: cauldron.png
chest: chest.png
enchantingTable: enchantingTable.png
jukebox: jukebox.png
craftingTable: craftingTable.png
noteblock: noteblock.png
web: web.png
breakAnimation: breakAnimation.png
sponge: sponge.png
mobSpawner: mobSpawner.png
endPortal: endPortal.png
dragonEgg: dragonEgg.png
endStone: endStone.png
glowstone: glowstone.png
netherBrick: netherBrick.png
netherrack: netherrack.png
soulSand: soulSand.png
flowerRed: flowerRed.png
flowerYellow: flowerYellow.png
saplingBirch: saplingBirch.png
saplingOak: saplingOak.png
saplingPine: saplingPine.png
woodOak: woodOak.png
woodBrich: woodBrich.png
woodPine: woodPine.png
woodTop: woodTop.png
leavesNormal: leavesNormal.png
leavesPine: leavesPine.png
wheat: wheat.png
farmland: farmland.png
reeds: reeds.png
cactus: cactus.png
shrub: shrub.png
deadShrub: deadShrub.png
tallGrass: tallGrass.png
lillyPad: lillyPad.png
mushroomRed: mushroomRed.png
mushroomBrown: mushroomBrown.png
netherWart: netherWart.png
mushroomGiantBrown: mushroomGiantBrown.png
mushroomGiantRed: mushroomGiantRed.png
mushroomGiantStem: mushroomGiantStem.png
mushroomGiantInside: mushroomGiantInside.png
vines: vines.png
melonStems: melonStems.png
melon: melon.png
pumpkin: pumpkin.png
woodPlanks: woodPlanks.png
glass: glass.png
glassPane: glassPane.png
stoneBrick: stoneBrick.png
stoneBrickCracked: stoneBrickCracked.png
stoneBrickMossy: stoneBrickMossy.png
oreBlockDiamond: oreBlockDiamond.png
oreBlockIron: oreBlockIron.png
oreBlockGold: oreBlockGold.png
oreBlockLapis: oreBlockLapis.png
brick: brick.png
water: water.png
lava: lava.png
grass: grass.png
dirt: dirt.png
dirtSide: dirtSide.png
grassSide: grassSide.png
snow: snow.png
snowSide: snowSide.png
ice: ice.png
stone: stone.png
oreCoal: oreCoal.png
oreIron: oreIron.png
oreGold: oreGold.png
oreDiamond: oreDiamond.png
oreRedstone: oreRedstone.png
oreLapis: oreLapis.png
cobblestone: cobblestone.png
cobblestoneMossy: cobblestoneMossy.png
gravel: gravel.png
sand: sand.png
sandstone: sandstone.png
clay: clay.png
obsidian: obsidian.png
bedrock: bedrock.png
mycelium: mycelium.png
myceliumSide: myceliumSide.png
woolWhite: woolWhite.png
woolBlack: woolBlack.png
woolGrey: woolGrey.png
woolRed: woolRed.png
woolPink: woolPink.png
woolGreen: woolGreen.png
woolGreenLime: woolGreenLime.png
woolBrown: woolBrown.png
woolYellow: woolYellow.png
woolBlue: woolBlue.png
woolBlueLight: woolBlueLight.png
woolPurple: woolPurple.png
woolMagenta: woolMagenta.png
woolCyan: woolCyan.png
woolOrange: woolOrange.png
woolGreyLight: woolGreyLight.png
